set dotenv-load := true

sql_config := "host=" + env_var('DATABASE_HOST') + " port=" + env_var('DATABASE_PORT') + " dbname=" + env_var('DATABASE_NAME') + " user=" + env_var('DATABASE_USER') + " password=" + env_var('DATABASE_PASSWORD')
pgquery := "psql -d " + sql_config
pgdump := "pg_dump -d " + sql_config + " --schema-only"
sql_dir := "./sql_sqc"
uv_python := "uv run python -m"

default:
    @just --list

clear:
    @clear

build-migration-up: clear
    @{{ uv_python }} src.scripts.build_migration_up

build-migration-seed: clear
    @{{ uv_python }} src.scripts.build_migration_seed

up: clear build-migration-up
    @{{ uv_python }} src.scripts.up

seed: clear build-migration-seed
    @{{ uv_python }} src.scripts.seed

truncate: clear
    @{{ uv_python }} src.scripts.truncate
