services:
  # ------------------------------------------------------------------------------

  webclient:
    container_name: ${WEBCLIENT_HOST}
    build:
      context: ../services/webclient
      dockerfile: ../../docker/webclient.Dockerfile
      target: dev
    env_file: ../.env
    expose:
      - ${WEBCLIENT_PORT}
    ports:
      - "${WEBCLIENT_PORT}:${WEBCLIENT_PORT}"
    networks:
      - traffic-lights-network
    volumes:
      - ../services/webclient:/usr/src/app
      - /usr/src/app/node_modules

  # ------------------------------------------------------------------------------

  api-server:
    container_name: ${APISERVER_HOST}
    build:
      context: ../services/api-server
      dockerfile: ../../docker/api-server.Dockerfile
      target: dev
    env_file: ../.env
    expose:
      - ${APISERVER_PORT}
    ports:
      - "${APISERVER_PORT}:${APISERVER_PORT}"
    networks:
      - traffic-lights-network
    volumes:
      - ../services/api-server:/usr/src/app
      - /usr/src/app/node_modules

  # ------------------------------------------------------------------------------

  database:
    image: kartoza/postgis
    container_name: ${DATABASE_HOST}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - traffic-lights-network
    volumes:
      - postgres_data:/var/lib/postgresql
      - ../services/db-migrator:/usr/src/app

  # ------------------------------------------------------------------------------

  database-adminer:
    image: dpage/pgadmin4
    container_name: ${DBADMINER_HOST}
    expose:
      - 80
    ports:
      - "${DBADMINER_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DBADMINER_USER}
      PGADMIN_DEFAULT_PASSWORD: ${DBADMINER_PASSWORD}
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    networks:
      - traffic-lights-network

  # ------------------------------------------------------------------------------

networks:
  traffic-lights-network:
    driver: bridge

  # ------------------------------------------------------------------------------

volumes:
  postgres_data:
